import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import productsRouter from "./products";
import serversRouter from "./servers";
import ordersRouter from "./orders";
import accountsRouter from "./accounts";
import balanceRouter from "./balance";
import dashboardRouter from "./dashboard";
import adminRouter from "./admin";
import settingsRouter from "./settings";
import webhookRouter from "./webhook";
import telegramBotRouter from "./telegram-bot";
import broadcastRouter from "./broadcast";
import exportRouter from "./export";
import balanceLogsRouter from "./balance-logs";
import backupRouter from "./backup";
import resellerRouter from "./reseller";
import vouchersRouter from "./vouchers";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(productsRouter);
router.use(serversRouter);
router.use(ordersRouter);
router.use(accountsRouter);
router.use(balanceRouter);
router.use(dashboardRouter);
router.use(adminRouter);
router.use(settingsRouter);
router.use(webhookRouter);
router.use(telegramBotRouter);
router.use(broadcastRouter);
router.use(exportRouter);
router.use(balanceLogsRouter);
router.use(backupRouter);
router.use(resellerRouter);
router.use(vouchersRouter);

export default router;
